[project]
name = "hb-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.13"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "selenium>=4.38.0",
    "webdriver-manager>=4.0.2",
]
